package HelloApp.HelloPackage;


/**
* HelloApp/HelloPackage/arraymioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 18, 2016 10:11:56 PM UTC
*/

public final class arraymioHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public arraymioHolder ()
  {
  }

  public arraymioHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.HelloPackage.arraymioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.HelloPackage.arraymioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.HelloPackage.arraymioHelper.type ();
  }

}
