package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 18, 2016 10:11:56 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  int[] sum (int[] a, int[] b);
  void shutdown ();
} // interface HelloOperations
