package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, January 16, 2016 8:37:24 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  String sum (String a, String b);
  void shutdown ();
} // interface HelloOperations
